[project]
name = "deklare"
version = "0.1.4"
description = "A data processing framework for data exploration"
authors = [
    { name = "Matthias Meyer", email = "contact@niowniow.net" },
    { name = "Jan Hochstrasser", email = "jhochstrasse@ethz.ch" }
]
dependencies = [
    "dask==2025.2.0",
    "pandas>=2.2.3",
    "zarr>=2.18.2",
    "compress-pickle>=2.1.0",
    "cachetools>=5.3.3",
    "numpy>=2",
    "pystac>=1.11.0",
    "shapely>=2.0.6",
    "tqdm>=4.67.1",
    "xarray>=2025.6.1",
    "pydantic>=2.12.4",
    "obstore>=0.9.0",
]
readme = "README.md"
requires-python = ">= 3.10"

[project.optional-dependencies]
examples = [
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "mypy>=1.17.1",
    "pip>=25.2",
    "pre-commit>=4.3.0",
    "ruff>=0.12.12",
]

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = [
  "E",
  "W",
  "F",
  "C901",
  "I",
  "N",
  "B",
  "A",
  "T20",
  "PT",
  "Q",
  "S",
  "ANN",
  "ARG",
]

ignore = [
    "S101",
    "S104",
]

[tool.ruff.lint.per-file-ignores]
"src/deklare/__init__.py" = ["F401"]

[tool.ruff.lint.mccabe]
max-complexity = 10
